---
- name: autofs-module
  yum: pkg=autofs state=latest


- name: autofs services
  service: name=autofs state=started enabled=yes 



- name:  auto.nf template file , 
  template: src=auto.nfs.j2 dest=/etc/auto.nfs  backup=yes owner=root group=root
  register: configure1


- name:  autofs.master.d/nfs.auto
  template: src=nfs.autofs.j2  dest=/etc/auto.master.d/nfs.autofs backup=yes owner=root group=root
  register: configure2



- name: autofs services
  service: name=autofs state=restarted enabled=yes
  when: configure1 is changed and configure2 is changed or configure1 is changed or  configure2 is changed 
