---
- hosts: docker-swarm-cluster
  become: yes
  gather_facts: yes
  ignore_errors: yes
  roles:
       - docker-mgt-users
       - packages
       - autofs
       - sudoers

- hosts: docker-swarm-cluster
  become: yes
  gather_facts: yes
  ignore_errors: yes
  roles:
       - docker-swarm

- hosts: master
  become: yes
  gather_facts: yes
  ignore_errors: yes
  roles:
       - registry


- hosts: master
  become: yes
  gather_facts: yes
  ignore_errors: yes
  roles:
       - bitbucket
